//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.16
//
package com.amazonaws.mobile;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 7566140f-77d8-4b8d-89d2-4327aef84721 aws-my-sample-app-android-v0.16";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("ap-northeast-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "ap-northeast-1:a4ef65bd-f3d1-416a-9d74-9c49a3d0dc61";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "tresurehunting-contentdelivery-mobilehub-482139222";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("ap-northeast-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "ap-northeast-1_JeOFtRku8";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "4v0t2h1lqlhne4ugg6v5m0nn2";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1roktn3uv55ccntf6gjr4o0plmn5cfe7hsa4mdnoj2iqou0aub8";

    private static final AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .withCognitoUserPool(AMAZON_COGNITO_USER_POOL_ID,
            AMAZON_COGNITO_USER_POOL_CLIENT_ID, AMAZON_COGNITO_USER_POOL_CLIENT_SECRET)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}
